app:
  database-access-type: jpa
  use-queue: true
  scheduler:
    enable: true
    interval: 100s
    force-check-delay: 100s
    checked-links-batch-size: 2
  retry:
    strategy-name: fixed # fixed, linear, exponential
    retry-numbers: 5
    interval: 500
    multiplier: 2.5
    retry-codes:
      - 500
      - 502
      - 503
  kafka:
    topic: bot-notify-topic
    bootstrap-servers: localhost:9092

bucket:
  limit-per-minute: 4

spring:
  application:
    name: scrapper
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
  liquibase:
    enabled: false

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

web-clients:
  stackoverflow:
    baseurl: https://api.stackexchange.com/2.3/
  github:
    baseurl: https://api.github.com/
  bot:
    baseurl: http://localhost:8090

springdoc:
  swagger-ui:
    path: /swagger-ui
