app:
  scheduler:
    enable: true
    interval: 2s
    force-check-delay: 2s

spring:
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

web-clients:
  stackoverflow:
    baseurl: https://api.stackexchange.com/2.3/
  github:
    baseurl: https://api.github.com/

