app:
  telegram-token: ${BOT_TOKEN}
  retry:
    strategy-name: fixed # fixed, linear, exponential
    retry-numbers: 5
    interval: 500
    multiplier: 2.5

    retry-codes:
      - 500
      - 502
      - 503

bucket:
  limit-per-minute: 100


spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

web-clients:
  scrapper:
    baseurl: http://localhost:8080

springdoc:
  swagger-ui:
    path: /swagger-ui
