app:
  telegram-token: ${BOT_TOKEN}
  retry:
    strategy-name: fixed # fixed, linear, exponential
    retry-numbers: 5
    interval: 500
    multiplier: 2.5
    retry-codes:
      - 500
      - 502
      - 503
  kafka:
    topic: bot-notify-topic
#    bootstrap-servers: localhost:9092
    bootstrap-servers: host.docker.internal:29092
    group-id: update-listener

bucket:
  limit-per-minute: 100

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  kafka:
    bootstrap-servers:  host.docker.internal:29092

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

web-clients:
  scrapper:
#    baseurl: http://localhost:8080
    baseurl: http://host.docker.internal:8080


springdoc:
  swagger-ui:
    path: /swagger-ui


management:
  server:
    port: 8091

  endpoints:
    web:
      base-path: /
      path-mapping:
        prometheus: /metrics
      exposure:
        include: info, health, prometheus

  metrics:
    tags:
      application: ${spring.application.name}

    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

